// ============================================
// Horizon Trader Platform — Activity Log Service
// ============================================

import { execute, type DbClient } from '../db/query';
import type { ActorType, TargetType } from '../types/index';

/**
 * Input for creating an activity log entry.
 *
 * All fields map directly to the `activity_logs` table columns.
 * The `id` and `created_at` are generated by the database.
 */
export interface ActivityLogInput {
  /** UUID of the actor (nullable for system actions) */
  actor_id?: string | null;
  /** Type of actor performing the action */
  actor_type: ActorType;
  /** Description of the action performed */
  action: string;
  /** Type of the target entity (nullable) */
  target_type?: TargetType | null;
  /** UUID of the target entity (nullable) */
  target_id?: string | null;
  /** Additional context as JSON (before/after state, metadata, etc.) */
  details?: Record<string, unknown> | null;
  /** IP address of the request origin (nullable) */
  ip_address?: string | null;
}

/**
 * Immutable activity log service — insert-only, no update or delete.
 *
 * Logs every platform action to the `activity_logs` table for audit trail
 * purposes. Supports all actor types: admin, member, system, external_api.
 *
 * **Validates: Requirements 23.1, 23.2, 23.7**
 */
export class ActivityLogService {
  /**
   * Insert a new activity log entry.
   *
   * @param entry - The log entry data
   * @param client - Optional database client for transaction support
   */
  async log(entry: ActivityLogInput, client?: DbClient): Promise<void> {
    await execute(
      `INSERT INTO activity_logs (actor_id, actor_type, action, target_type, target_id, details, ip_address)
       VALUES ($1, $2, $3, $4, $5, $6, $7)`,
      [
        entry.actor_id ?? null,
        entry.actor_type,
        entry.action,
        entry.target_type ?? null,
        entry.target_id ?? null,
        entry.details ? JSON.stringify(entry.details) : null,
        entry.ip_address ?? null,
      ],
      client,
    );
  }
}
